#include "board_layout.h"

#include <stdlib.h>
#include <ti/drivers/gpio/GPIOCC26XX.h>

#include "gpio_drv.h"
#include "sys_config.h"

const Pin_t PinTable[DIO_CNT] = {
 {GPIOCC26XX_DIO_12, 18,  0,   "MCU_TX", NULL, GPIOCC26XX_DIO_12,PIN_PUSHPULL},
 {GPIOCC26XX_DIO_13, 19,  0,   "MCU_RX", NULL, GPIOCC26XX_DIO_13|GPIO_CFG_IN_NOPULL, PIN_INPUT_EN},
 {DIO_PS_RS232,      12,  0, "PS_RS232", NULL, DIO_PS_RS232 | GPIO_CFG_OUT_STD | GPIO_CFG_OUT_STR_MED | GPIO_CFG_OUT_LOW, 6 | PIN_GPIO_OUTPUT_EN | PIN_GPIO_LOW | PIN_PUSHPULL | PIN_DRVSTR_MED},
 {DIO_LED_RED,       39,  0,    "R_LED", NULL, DIO_LED_RED | GPIO_CFG_OUT_STD | GPIO_CFG_OUT_STR_MED | GPIO_CFG_OUT_LOW, 6 | PIN_GPIO_OUTPUT_EN | PIN_GPIO_LOW | PIN_PUSHPULL | PIN_DRVSTR_MED},
 {DIO_LED_GREEN,     43,  0,    "G_LED", NULL, DIO_LED_GREEN | GPIO_CFG_OUT_STD | GPIO_CFG_OUT_STR_MED | GPIO_CFG_OUT_LOW, 7 | PIN_GPIO_OUTPUT_EN | PIN_GPIO_LOW | PIN_PUSHPULL | PIN_DRVSTR_MED},
 {GPIOCC26XX_DIO_16, 26,  0,      "TDO", NULL, GPIOCC26XX_DIO_16, PIN_INPUT_EN},
 {GPIOCC26XX_DIO_17, 27,  0,      "TDI", NULL, GPIOCC26XX_DIO_17, PIN_INPUT_EN},
};



