
#ifndef NVS_MEMORY_LAYOUT_H
#define NVS_MEMORY_LAYOUT_H

#include "flash_drv.h"

#define FLASH_FS_PAGE_SIZE  (2*FLASH_SECTOR_SIZE)
#define NVS_SIZE (2*FLASH_FS_PAGE_SIZE) /*Must be double multiple of FLASH_SECTOR_SIZE*/

#define NVS_FLASH_START (NOR_FLASH_END-NVS_SIZE)

/* page 1 */
#define MEMORY_MANAGER1_OFFSET	NVS_FLASH_START
#define MEMORY_MANAGER1_LENGTH	FLASH_FS_PAGE_SIZE

/* page 2 */
#define MEMORY_MANAGER2_OFFSET	NVS_FLASH_START+FLASH_FS_PAGE_SIZE
#define MEMORY_MANAGER2_LENGTH	FLASH_FS_PAGE_SIZE

#endif /* NVS_MEMORY_LAYOUT_H */
