################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C55_SRCS := 
A_SRCS := 
CFG_UPPER_SRCS := 
CFG_SRCS := 
ASM_UPPER_SRCS := 
PINMUX_SRCS := 
EXE_SRCS := 
LDS_UPPER_SRCS := 
CPP_SRCS := 
CMD_SRCS := 
O_SRCS := 
ELF_SRCS := 
C??_SRCS := 
C64_SRCS := 
C67_SRCS := 
SA_SRCS := 
S64_SRCS := 
OPT_SRCS := 
CXX_SRCS := 
S67_SRCS := 
S??_SRCS := 
PDE_SRCS := 
SV7A_SRCS := 
SYSCFG_SRCS := 
K_SRCS := 
CLA_SRCS := 
S55_SRCS := 
LD_UPPER_SRCS := 
OUT_SRCS := 
INO_SRCS := 
LIB_SRCS := 
ASM_SRCS := 
S_UPPER_SRCS := 
SYSCONFIG_SRCS := 
S43_SRCS := 
LD_SRCS := 
CMD_UPPER_SRCS := 
C_UPPER_SRCS := 
C++_SRCS := 
C43_SRCS := 
OBJ_SRCS := 
LDS_SRCS := 
S_SRCS := 
CC_SRCS := 
S62_SRCS := 
C62_SRCS := 
C_SRCS := 
C55_DEPS := 
C_UPPER_DEPS := 
S67_DEPS := 
S62_DEPS := 
S_DEPS := 
OPT_DEPS := 
C??_DEPS := 
ASM_UPPER_DEPS := 
S??_DEPS := 
C64_DEPS := 
CXX_DEPS := 
S64_DEPS := 
INO_DEPS := 
GEN_CMDS := 
GEN_FILES := 
CLA_DEPS := 
S55_DEPS := 
SV7A_DEPS := 
EXE_OUTPUTS := 
C62_DEPS := 
C67_DEPS := 
PDE_DEPS := 
GEN_MISC_DIRS := 
K_DEPS := 
C_DEPS := 
CC_DEPS := 
BIN_OUTPUTS := 
GEN_OPTS := 
C++_DEPS := 
C43_DEPS := 
S43_DEPS := 
OBJS := 
ASM_DEPS := 
GEN_MISC_FILES := 
S_UPPER_DEPS := 
CPP_DEPS := 
SA_DEPS := 
C++_DEPS__QUOTED := 
OPT_DEPS__QUOTED := 
S_UPPER_DEPS__QUOTED := 
SA_DEPS__QUOTED := 
C??_DEPS__QUOTED := 
S67_DEPS__QUOTED := 
GEN_MISC_DIRS__QUOTED := 
C55_DEPS__QUOTED := 
CC_DEPS__QUOTED := 
ASM_UPPER_DEPS__QUOTED := 
SV7A_DEPS__QUOTED := 
S??_DEPS__QUOTED := 
OBJS__QUOTED := 
C67_DEPS__QUOTED := 
K_DEPS__QUOTED := 
S55_DEPS__QUOTED := 
GEN_CMDS__QUOTED := 
GEN_MISC_FILES__QUOTED := 
INO_DEPS__QUOTED := 
C62_DEPS__QUOTED := 
C_DEPS__QUOTED := 
C_UPPER_DEPS__QUOTED := 
C43_DEPS__QUOTED := 
CPP_DEPS__QUOTED := 
BIN_OUTPUTS__QUOTED := 
GEN_FILES__QUOTED := 
C64_DEPS__QUOTED := 
CXX_DEPS__QUOTED := 
CLA_DEPS__QUOTED := 
S_DEPS__QUOTED := 
ASM_DEPS__QUOTED := 
S43_DEPS__QUOTED := 
EXE_OUTPUTS__QUOTED := 
S64_DEPS__QUOTED := 
S62_DEPS__QUOTED := 
PDE_DEPS__QUOTED := 
GEN_OPTS__QUOTED := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
Drivers/bmp180 \
Drivers/boot_drv \
Drivers/bq25171_q1_drv \
Drivers/cli_drv \
Drivers/ext_ram_simulator \
Drivers/flash_fs \
Drivers/gpio_pwm \
Drivers/led_drv \
Drivers/lora \
Drivers/mx25l6433f \
Drivers/params \
Drivers/pwr_mux \
Drivers/rs232_drv \
Drivers/sx1262 \
Drivers/task_drv \
Drivers/tcan4550_q1 \
Drivers/tcan4550_q1_ti \
Drivers/telematic \
Drivers/zed_f9p \
Drivers_vendor/NV \
OAD \
Profiles \
Startup \
boards/harvester_cc2642_v1 \
boards/harvester_v1 \
boards/launchpad \
boards/stm32_H407 \
boards/tBeamV1_1 \
bsp_cc26x2/adc \
bsp_cc26x2/ble \
bsp_cc26x2/bluetooth \
bsp_cc26x2/bluetooth/roles/cc26xx \
bsp_cc26x2/bluetooth/serial_port/CC26xx \
bsp_cc26x2/bluetooth/spp_ble_server \
bsp_cc26x2/clocks \
bsp_cc26x2/core_drv \
bsp_cc26x2/dac \
bsp_cc26x2/flash \
bsp_cc26x2/flash_nvs \
bsp_cc26x2/gpio \
bsp_cc26x2/i2c \
bsp_cc26x2/interrupt \
bsp_cc26x2/rf \
bsp_cc26x2/rng \
bsp_cc26x2/rtc \
bsp_cc26x2/spi \
bsp_cc26x2 \
bsp_cc26x2/syscfg \
bsp_cc26x2/tim \
bsp_cc26x2/uart \
bsp_cc26x2/watchdog \
common \
components/calendar \
components/system \
iCall \
iCallBLE \
utils \
utils/crc \
utils/fifo \
utils/io_utils \
utils/utils_diag \
utils/utils_files \
utils/utils_math \
utils/utils_string \
utils/utils_sys \
utils/win_utils \

