NMEA_PROTO_DIR = $(PROJECT_ROOT)protocols/nmea_protocol
#@ echo $(error NMEA_PROTO_DIR = $(NMEA_PROTO_DIR)) 
#@ echo $(error CFLAGS = $(CFLAGS))

INCDIR += -I$(NMEA_PROTO_DIR)

OPT += -DHAS_NMEA
OPT += -DHAS_NMEA_DIAG

OPT += -DHAS_NMEA_GGA
OPT += -DHAS_NMEA_GLL
OPT += -DHAS_NMEA_GSA
OPT += -DHAS_NMEA_GSV
OPT += -DHAS_NMEA_PBUX
OPT += -DHAS_NMEA_RMC
OPT += -DHAS_NMEA_VTG
OPT += -DHAS_NMEA_ZDA

SOURCES_C += $(NMEA_PROTO_DIR)/nmea_diag.c
SOURCES_C += $(NMEA_PROTO_DIR)/nmea_protocol.c
