
#OPT += -DHAS_TEST_SUIT_NMEA_PROTO
#OPT += -DHAS_TEST_SUIT_CONVERT
OPT += -DHAS_UTESTS
#OPT += -DHAS_TEST_SUIT_CRC
#OPT += -DHAS_TEST_SUIT_STRING_UTILS
#OPT += -DHAS_TEST_SUIT_UBLOX_PROTO
#OPT += -DHAS_TEST_SUIT_TBFP_RTCM
#OPT += -DHAS_TEST_CLI
#OPT += -DHAS_TEST_SUIT_CALENDAR
#OPT += -DHAS_TEST_SUIT_FIFO
#OPT += -DHAS_TEST_SUIT_RTCM3_PROTO
#OPT += -DHAS_TEST_SUIT_TBFP
#OPT += -DHAS_TEST_SUIT_UTILS_GNSS
OPT += -DHAS_TEST_SUIT_UTILS

